apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: josecarlosanpedrokubernetesnodejs 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: josecarlosanpedrokubernetesnodejs 
    spec:
      containers:
        - name: josecarlosanpedrokubernetesnodejs 
          image: josecarlosanpedro.azurecr.io/josecarlosanpedrokubernetesnodejs
          ports:
          - containerPort: 80