apiVersion : apps/v1
kind: Deployment
metadata:
  name: josecarlosanpedrokubernetesnodejs 
spec:
  replicas: 1
  selector:
    matchLabels:
      name: josecarlosanpedrokubernetesnodejs-pod
      app: josecarlosanpedrokubernetesnodejs
  template:
    metadata:
      labels:
        app: josecarlosanpedrokubernetesnodejs 
    spec:
      containers:
        - name: josecarlosanpedrokubernetesnodejs 
          image: josecarlosanpedro.azurecr.io/josecarlosanpedrokubernetesnodejs
          ports:
          - containerPort: 80