apiVersion : apps/v1
kind: Deployment
metadata:
  name: josecarlosanpedrokubernetesnodejs-deploy
  labels:
    name: josecarlosanpedrokubernetesnodejs-deploy
    app: josecarlosanpedrokubernetesnodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      name: josecarlosanpedrokubernetesnodejs-pod
      app: josecarlosanpedrokubernetesnodejs
  template:
    metadata:
      name: josecarlosanpedrokubernetesnodejs-pod
      labels:
        name: josecarlosanpedrokubernetesnodejs-pod
        app: josecarlosanpedrokubernetesnodejs
    spec:
      containers:
        - name: josecarlosanpedrokubernetesnodejs 
          image: josecarlosanpedro.azurecr.io/josecarlosanpedrokubernetesnodejs
          ports:
          - containerPort: 80